// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(app) {
    return app.log('Write your startup code / helpers to application.coffee - or any file in /configs/!');
  };

}).call(this);
