// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app) {
    var coffee, sass;
    coffee = require('coffee-script');
    sass = require('node-sass');
    app.compiler['.coffee'] = function(file) {
      var _this = this;
      return app.fs.readFile(file, 'utf8', function(err, rawCode) {
        var cs, error;
        if (err) {
          console.log(app.colors.red + 'compileAsset() error:' + app.colors.reset, err);
        }
        console.log(app.colors.cyan + 'CoffeeScript:' + app.colors.reset, file.replace(app.cfg.path, ''));
        try {
          cs = coffee.compile(rawCode);
        } catch (_error) {
          error = _error;
          return console.log(app.colors.red + 'CoffeeScript error:' + app.colors.reset, file.replace(app.cfg.path, '') + ':', error.message, "on lines:", error.location.first_line + '-' + error.location.last_line);
        }
        if (error == null) {
          return app.fs.writeFile(file.replace('.coffee', '.js'), cs, function(err) {
            if (err) {
              return console.log(app.colors.red + 'autocompile write error! file' + app.colors.reset, file.replace('.coffee', '.js'), 'error:', err);
            }
          });
        }
      });
    };
    return app.compiler['.scss'] = function(file) {
      var _this = this;
      return sass.render({
        file: file,
        success: function(css) {
          return app.fs.writeFile(file.replace('.scss', '.css'), css, function(err) {
            if (err) {
              return console.log(app.colors.red + 'autocompile write error! file' + app.colors.reset, file.replace('.scss', '.css'), 'error:', err);
            }
          });
        },
        error: function(error) {
          return console.log('SCSS Compile error:', error);
        }
      });
    };
  };

}).call(this);
