// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app) {
    return console.log('Write your startup code / helpers to application.coffee - or any file in /cfg/!');
  };

}).call(this);
