// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(app) {
    return {
      '*': function() {},
      home: function(req, res) {
        return void 0;
      }
    };
  };

}).call(this);
