// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(app) {
    return {
      '*': function() {},
      home: function(req, res) {},
      hello: function() {
        return "Hello World!";
      },
      api: function() {
        return {
          some: 'json'
        };
      },
      someView: function() {
        return void 0;
      }
    };
  };

}).call(this);
