// Generated by CoffeeScript 1.7.1
(function() {
  var Skinnyjs,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  module.exports = Skinnyjs = (function() {
    function Skinnyjs(cfg) {
      var key, value, _ref;
      this.cfg = cfg;
      this.path = require('path');
      this._ = require('underscore');
      this.fs = require('fs');
      if (this.cfg == null) {
        this.cfg = {};
      }
      if (this.cfg.env == null) {
        this.cfg.env = 'dev';
      }
      if (this.cfg.port == null) {
        this.cfg.port = 9000;
      }
      if (this.cfg.reload == null) {
        this.cfg.reload = true;
      }
      if (this.cfg.db == null) {
        this.cfg.db = '127.0.0.1:27017';
      }
      if (this.cfg.path == null) {
        this.cfg.path = this.path.normalize(process.cwd());
      }
      if (this.cfg.project == null) {
        this.cfg.project = this.cfg.path.split(this.path.sep).splice(-1)[0];
      }
      if (this.cfg.layout == null) {
        this.cfg.layout = {
          app: '/app',
          configs: '/configs',
          test: '/test',
          models: '/app/models',
          views: '/app/views',
          controllers: '/app/controllers',
          assets: '/app/client'
        };
      }
      _ref = this.cfg.layout;
      for (key in _ref) {
        value = _ref[key];
        this.cfg.layout[key] = this.path.normalize(this.cfg.path + this.cfg.layout[key]);
      }
      this.cfg.moduleTypes = ['configs', 'models', 'controllers'];
      this.clr = {
        red: "\u001b[31m",
        blue: "\u001b[34m",
        green: "\u001b[32m",
        cyan: "\u001b[36m",
        reset: "\u001b[0m"
      };
      this.db = false;
      this.controllers = {};
      this.models = {};
      this.routes = {};
      this.configs = {};
      this.compiler = {};
      this.cache = {};
    }

    Skinnyjs.prototype.initModel = function(model, name) {
      var bind, protoInstance, skinny;
      if (model !== void 0) {
        skinny = this;
      } else {
        return model;
      }
      bind = function(instance) {
        var method, methodName;
        instance.save = protoInstance.save;
        instance.remove = protoInstance.remove;
        for (methodName in model) {
          method = model[methodName];
          if (model.hasOwnProperty(methodName)) {
            if (methodName !== 'find' && methodName !== 'new' && methodName !== 'remove' && methodName !== 'collection' && methodName !== 'prototype' && methodName !== '__super__') {
              instance[methodName] = method;
            }
          }
        }
        return instance;
      };
      protoInstance = {
        save: function(cb) {
          var error, k, out, v;
          out = {
            _id: this._id
          };
          for (k in this) {
            v = this[k];
            if (typeof v !== "function") {
              if (k !== 'prototype' && k !== '__super__') {
                out[k] = v;
              }
            }
          }
          try {
            return skinny.db.collection(name).save(out, function() {
              if (cb != null) {
                return cb();
              }
            });
          } catch (_error) {
            error = _error;
            return skinny.error(error, {
              type: 'database',
              error: 'modelSaveException',
              details: error.message
            });
          }
        },
        remove: function(cb) {
          if (this._id == null) {
            if (cb != null) {
              cb();
              return true;
            }
          }
          return skinny.db.collection(name).remove({
            _id: this._id
          }, function() {
            if (cb != null) {
              return cb();
            }
          });
        }
      };
      if (model.find == null) {
        model.find = function(query, cb) {
          if (typeof query === 'function') {
            cb = query;
            query = {};
          }
          return skinny.db.collection(name).find(query).toArray((function(_this) {
            return function(err, results) {
              var instance, _i, _len;
              for (_i = 0, _len = results.length; _i < _len; _i++) {
                instance = results[_i];
                instance = bind(instance);
              }
              return cb(results);
            };
          })(this));
        };
      }
      if (model["new"] == null) {
        model["new"] = function() {
          return bind({});
        };
      }
      if (model.remove == null) {
        model.remove = function(query, cb) {
          if (typeof query === 'function') {
            cb = query;
            query = {};
          }
          if (cb === void 0) {
            cb = function() {
              return true;
            };
          }
          return skinny.db.collection(name).remove(query, cb);
        };
      }
      if (model.collection == null) {
        model.collection = (function(_this) {
          return function() {
            return _this.db.collection(name);
          };
        })(this);
      }
      return model;
    };

    Skinnyjs.prototype.initModule = function(type, opts) {
      var error, isClient, isntJavascript, module;
      if (opts.path == null) {
        return false;
      } else {
        this.path.normalize(opts.path);
      }
      isntJavascript = !!!opts.path.match(/\.js$/);
      isClient = !!opts.path.match(/\/client\//);
      if (isntJavascript || isClient) {
        return true;
      }
      if (!!opts.path.match(/\/test\/*.js$/)) {
        return false;
      }
      if (__indexOf.call(this.cfg.moduleTypes, type) < 0) {
        this.log(this.clr.cyan + 'Unhandled change on:' + this.clr.reset, opts.path, this.clr.cyan + "you may want to restart Skinny" + this.clr.reset);
        return false;
      }
      opts.name = opts.name != null ? opts.name : opts.path.split(this.path.sep).splice(-1)[0].replace('.js', '');
      if (opts.force != null) {
        delete require.cache[require.resolve(opts.path)];
        delete this[type][opts.name];
      }
      try {
        module = require(this.path.normalize(opts.path));
      } catch (_error) {
        error = _error;
        return this.error(error, {
          type: type,
          error: 'moduleRequireException',
          details: opts
        });
      }
      if (typeof module !== 'function') {
        this[type][opts.name] = module;
        return true;
      }
      if (type === "models") {
        try {
          this[type][opts.name] = this.initModel(module(this, opts), opts.name);
        } catch (_error) {
          error = _error;
          return this.error(error, {
            type: type,
            error: 'moduleExecutionException',
            details: opts
          });
        }
      } else {
        this[type][opts.name] = module(this, opts);
      }
      return true;
    };

    Skinnyjs.prototype.log = function() {
      if (this.cfg.env === 'dev') {
        return console.log.apply(this, arguments);
      }
    };

    Skinnyjs.prototype.error = function(error, opts) {
      if (this.cfg.env === 'dev' && (this.io != null)) {
        this.io.sockets.emit('__skinnyjs', {
          error: {
            message: error.message,
            raw: error.toString(),
            module: opts
          }
        });
      }
      this.log(this.clr.red + 'Exception: ' + opts.error + this.clr.reset, 'in', ((opts.details != null) && (opts.details.name != null) ? '"' + opts.details.name + '":' : opts), error.toString());
      if (error.stack != null) {
        this.log("\n" + this.clr.cyan + "stack:" + this.clr.reset, error.stack);
      }
      if (opts.details != null) {
        return this.log(this.clr.cyan + "the Skinny:" + this.clr.reset, opts.details);
      }
    };

    Skinnyjs.prototype.init = function(cb) {
      var error, moduleType, watched, _i, _j, _len, _len1, _ref, _ref1, _results;
      this.express = require('express');
      this.server = this.express();
      this.mongo = require('mongodb');
      this.mongo.MongoClient.connect('mongodb://' + this.cfg.db + '/' + this.cfg.project, (function(_this) {
        return function(err, db) {
          if (err) {
            return _this.log(_this.clr.red + 'MongoDB error:' + _this.clr.reset, err);
          } else {
            return _this.db = db;
          }
        };
      })(this));
      _ref = this.cfg.moduleTypes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        moduleType = _ref[_i];
        this.fs.readdirSync(this.cfg.layout[moduleType]).forEach((function(_this) {
          return function(path) {
            if (_this.fileMatch(path)) {
              return _this.initModule(moduleType, {
                path: _this.cfg.layout[moduleType] + _this.path.sep + path
              });
            }
          };
        })(this));
      }
      if (cb != null) {
        cb(this);
      }
      this.server.use(this.express.json());
      this.server.use(this.express.compress());
      this.server.use('/views', this.express["static"](this.cfg.layout.views));
      this.server.use('/assets', this.express["static"](this.cfg.layout.assets));
      this.httpd = require('http').createServer(this.server);
      try {
        this.httpd.listen(this.cfg.port, (function(_this) {
          return function() {
            return _this.log('-->', _this.clr.green + 'Listening on port:' + _this.clr.reset, _this.cfg.port);
          };
        })(this));
      } catch (_error) {
        error = _error;
        return this.error(error, {
          type: 'skinnyCore',
          error: 'httpListenException'
        });
      }
      try {
        this.io = require('socket.io').listen(this.httpd, {
          log: false
        });
      } catch (_error) {
        error = _error;
        return this.error(error, {
          type: 'skinnyCore',
          error: 'socketioListenException'
        });
      }
      if (this.cfg.reload) {
        this.watch = require('node-watch');
        _ref1 = ['app', 'configs', 'test'];
        _results = [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          watched = _ref1[_j];
          _results.push(this.watch(this.cfg.layout[watched], (function(_this) {
            return function(file) {
              return _this.fileChangeEvent(file);
            };
          })(this)));
        }
        return _results;
      }
    };

    Skinnyjs.prototype.fileMatch = function(file) {
      if (file.match(/\/\.git|\.swp$|\.tmp$/)) {
        return false;
      } else {
        return true;
      }
    };

    Skinnyjs.prototype.fileChangeEvent = function(file) {
      var compile, exists;
      if (this.fileMatch(file)) {
        if (exists = this.fs.existsSync(file)) {
          if (this.fs.lstatSync(file).isDirectory()) {
            return false;
          }
          if (compile = this.compiler[this.path.extname(file)]) {
            return compile(file);
          }
        } else {
          if (this.cache[file] != null) {
            delete this.cache[file];
          }
        }
        if (this.initModule(file.split(this.path.sep).splice(-2)[0], {
          path: file,
          force: true,
          clear: !exists
        })) {
          this.log('-->', this.clr.green + 'Reloading browser' + this.clr.reset, '-', file.replace(this.cfg.path, ''));
          return this.io.sockets.emit('__skinnyjs', {
            reload: {
              delay: 0
            }
          });
        }
      }
    };

    Skinnyjs.prototype.install = function(target, cb) {
      if (target == null) {
        target = this.cfg.path + dirName;
      }
      if (!this.fs.existsSync(target)) {
        this.fs.mkdirSync(target);
      }
      return require('ncp').ncp(__dirname + '/templateProject', target, function(err) {
        if (err) {
          this.log(err);
        }
        if (cb != null) {
          return cb();
        }
      });
    };

    Skinnyjs.prototype.parseRoutes = function() {
      return this._.each(this.routes, (function(_this) {
        return function(obj, route) {
          return _this.server[obj.method || 'get'](route, function(req, res) {
            var controllerOutput, error;
            if (_this.controllers[obj.controller] != null) {
              if (_this.controllers[obj.controller]['*'] != null) {
                _this.controllers[obj.controller]['*'](req, res);
              }
            }
            _this.log('(' + req.connection.remoteAddress + ')', _this.clr.cyan + req.method + ':' + _this.clr.reset, req.url, obj.controller + '#' + obj.action);
            res.view = _this.cfg.layout.views + '/' + obj.controller + '/' + obj.action + '.html';
            if ((_this.controllers[obj.controller] != null) && (_this.controllers[obj.controller][obj.action] != null)) {
              try {
                controllerOutput = _this.controllers[obj.controller][obj.action](req, res);
              } catch (_error) {
                error = _error;
                _this.error(error, {
                  error: 'controllerException',
                  details: {
                    name: obj.controller,
                    action: obj.controller
                  }
                });
              }
              if (controllerOutput != null) {
                if (controllerOutput.skip != null) {
                  return false;
                }
                if (res.headersSent) {
                  return false;
                }
                if (typeof controllerOutput === "object") {
                  controllerOutput = JSON.stringify(controllerOutput);
                }
                if (controllerOutput != null) {
                  return res.send(controllerOutput);
                }
              }
            }
            if (res.headersSent) {
              return false;
            }
            if (_this.cache[res.view] == null) {
              _this.cache[res.view] = _this.fs.existsSync(res.view);
            }
            if (_this.cache[res.view]) {
              return res.sendfile(res.view);
            } else {
              return res.send('404');
            }
          });
        };
      })(this));
    };

    return Skinnyjs;

  })();

}).call(this);
