// Generated by CoffeeScript 1.7.1
(function() {
  var asset, fs, path, skinny, skinnyjs, testOne;

  asset = require('assert');

  path = require('path');

  fs = require('fs');

  skinnyjs = require('../../skinnyjs/lib/skinny.js');

  skinny = new skinnyjs({
    port: 9001,
    reload: true,
    path: __dirname + '/../',
    env: 'test'
  });

  testOne = function() {
    return describe("skinny", function() {
      return describe(".init()", function() {
        return it("should boot correctly", function(initComplete) {
          return skinny.init(function(app) {
            app.server.use(app.express.urlencoded());
            app.server.use('/assets', app.express["static"](app.cfg.layout.assets));
            initComplete();
            if (typeof testTwo !== "undefined" && testTwo !== null) {
              return testTwo();
            }
          });
        });
      });
    });
  };

  testOne();

}).call(this);
